# Adds namespace to all resources.
namespace: data-science

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: data-

# Labels to add to all resources and selectors.
commonLabels:
  app: seldon
  app.kubernetes.io/name: seldon
  app.kubernetes.io/version: v0.5
  app.kubernetes.io/instance: seldon1
    
bases:
- ../manager

resources:
- role_binding.yaml
#- role_webhook.yaml
- role_binding_webhook.yaml
- role_binding_sas.yaml
- leader_election_role_binding.yaml
- role_sas.yaml
# Comment the following line if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
#- auth_proxy_service.yaml

patchesStrategicMerge:
- patch_configmap.yaml
- patch_manager_env.yaml
- manager_webhook_patch.yaml

