apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: data-science
spec:
  template:
    spec:
      containers:
      - env:
        - name: MANAGER_CREATE_RESOURCES
          value: "true"
        name: manager
